/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "Starting game...": "正在开始游戏...",
    "Preparing the world.": "正在准备世界。",
    "Audio": "音频",
    "ATTACKING": "攻击中",
    "Attack": "攻击",
    "Bank": "银行",
    "Bonus:": "加成:",
    "Combat": "战斗",
    "Close": "关闭",
    "Combat Settings": "战斗设置",
    "Continue": "继续",
    "Enemy": "敌人",
    "Year": "年",
    "Troops Produced": "产出部队",
    "Area": "区域",
    "Copy Invite": "复制邀请",
    "Cost Sort": "成本排序",
    "Number format": "数字格式",
    "Debug": "调试",
    "Paused": "已暂停",
    "Pause": "暂停",
    "Player": "玩家",
    "Population": "人口",
    "Quests": "任务",
    "Refresh": "刷新",
    "Research": "研究",
    "Reset Game": "重置游戏",
    "Select an empire.": "选择一个帝国.",
    "Show Updates": "显示更新",
    "Show Whole Map": "显示完整地图",
    "Total Attack Multiplier": "总攻击乘数",
    "Total Research Multiplier": "总研究乘数",
    "Total Population Produced": "总产出人口",
    "Total Population Created": "总创造人口",
    "Total Owned Hexes": "总计拥有六边形地块",
    "No enemy empire selected.": "未选定任何敌对帝国。",
    "Player Hex": "玩家六边形地块",
    "Player Route Numbers": "玩家路线编号",
    "Player Troop Stats": "玩家部队属性",
    "Community": "社区",
    "Core Kept Area": "核心保留区域",
    "Completed quests": "完成任务",
    "Age of Carved Stone": "石刻时代",
    "Enemy Empire": "敌对帝国",
    "Enemy Empires": "敌对帝国",
    "Enemy Frontline": "敌方前线",
    "Enemy Troop Stats": "敌方部队属性",
    "📜 Dynasty History": "📜 朝代历史",
    "Full Cards": "完整卡片",
    "All quests complete": "所有任务已完成",
    "Age of Embers": "余烬时代",
    "Ancient Wisdom": "古老智慧",
    "Ashen Continuance": "灰烬永续",
    "Expression": "表达式",
    "End Sovereign Life": "结束王权生命",
    "Expression Viewer": "表达式查看器",
    "Fast-forwarding the hourglass. Please wait.": "快进沙漏。请稍等。",
    "Fertile Lands": "肥沃的土地",
    "First Banner Raised": "升起第一面旗帜",
    "First Discovery": "首次发现",
    "Hide": "隐藏",
    "HP": "生命值",
    "Infinity": "无限",
    "Kept Troops": "保持部队",
    "Kept Population": "保持人口",
    "Last Ember Omen": "余烬预兆",
    "Legacy": "遗物",
    "Load Game": "加载游戏",
    "Load from File": "从文件加载",
    "Logic": "逻辑",
    "Map": "地图",
    "Max Troops Reached": "最大到达军队",
    "Max Distance Reached": "最大到达距离",
    "Max Player Radius": "最大玩家半径",
    "Max Population": "最大人口",
    "Max Population": "最大半径",
    "Render": "渲染",
    "Progress / Loss": "进度 / 损失",
    "Progress Stats": "进度统计",
    "Ravaged Capital": "遭受重创的首都",
    "Population Paths": "人口路径",
    "Reach the Age of Carved Stone.": "达到石刻时代。",
    "Requirements": "要求",
    "Preferences": "首选项",
    "Scientific (8.00e4)": "科学计数法 (8.00e4)",
    "Save to File": "保存到文件",
    "Save Game": "保存游戏",
    "Save every tick (20-slot ring)": "",
    "Hex Area": "六边形地块区域",
    "Hex Span": "六边形地块跨度",
    "Hex span:": "六边形地块跨度:",
    "Hide completed legacy traits": "隐藏已完成的遗物特质",
    "Hide completed research": "隐藏已完成的研究",
    "Hide Population Numbers": "隐藏人口数字",
    "Hide unlocked achievements": "隐藏已解锁成就",
    "Hit Points": "生命值",
    "Horde": "部落",
    "Horde at the Border": "边境上的部落",
    "Horde Slayer": "部落杀手",
    "Horde Tribute": "部落贡品",
    "Horde Bane": "部落克星",
    "Horde Defeated": "部落被击败了",
    "Important Totals": "重要总数",
    "Infinity mode dormant.": "无限模式已休眠。",
    "Leadership Decay Delay": "领导衰变延迟",
    "Leadership Delay": "领导延迟",
    "Leadership Slope": "领导坡度",
    "Leadership Floor": "领导楼层",
    "Max Radius": "最大半径",
    "Manual Allocation": "手动分配",
    "Map Visuals": "地图视觉效果",
    "More": "更多",
    "Miss": "未命中",
    "Moon Rites": "月之仪式",
    "Notification": "通知",
    "Relentless Tide": "无情的浪潮",
    "Ring of Huts": "茅屋之环",
    "Stats": "统计",
    "Stationed Troops": "驻军部队",
    "Growth Floor": "增长上限",
    "Hearth Muster Mastery": "炉台集结精通",
    "Meters / Tick": "米 / Tick",
    "Next Age": "下一个时代",
    "Next Horde": "下一个部落",
    "No enemy empire selected": "没有选择敌人帝国",
    "No past rulers yet. You are the first!": "暂无过往统治者。你是第一位！",
    "You have finished every quest.": "你已经完成了所有的任务。",
    "You have not completed any quests yet.": "您目前还没有完成任何任务。",
    "Your Frontline": "你的前线",
    "Your Troop Stats": "您的部队属性",
    "Campfire Trails": "篝火小径",
    "Complete quest": "完成任务",
    "Complete the age quest to unlock.": "完成时代任务以解锁。",
    "Crest": "纹章",
    "Current Age": "当前时代",
    "Current quest": "当前任务",
    "Crownbreaker Standards": "皇冠破坏者标准",
    "Crownbreaker": "皇冠破坏者",
    "Current Scale State": "当前规模状态",
    "Decay Slope": "衰变斜率",
    "Decay Delay": "衰变延迟",
    "Defeat Attacking Empires": "击败侵略帝国",
    "Defense Softness": "防守松懈",
    "Defense": "防御",
    "DECLARE WAR": "宣战",
    "Enable or mute game notifications.": "启用或关闭游戏通知。",
    "Endless conquest begins here": "无尽的征服从此开始",
    "Endure 10 war ticks without losing territory.": "历经 10 场战争的考验，却依然保有领土不被侵占。",
    "Foundry of Souls": "灵魂铸造厂",
    "Galaxy may block direct Discord tabs from the embedded game. Copy this invite and open it in your browser.": "Galaxy 可能会阻止直接打开 Discord 界面的嵌入式链接。请复制此邀请链接，并在您的浏览器中打开它。",
    "Game Management": "游戏管理",
    "Game Sounds": "游戏声音",
    "Golden Age": "黄金时代",
    "Game Ticks": "游戏 Tick",
    "Growth Decay": "增长衰减",
    "in the 🧪 Research tab. Earn points and purchase it to unlock migration.": "在“🧪 研究”选项卡中。获取点数并购买它以解锁迁移功能。",
    "Leadership Decay Delay": "领导力衰退延缓",
    "Max Supported Troops": "最大支援部队",
    "Rescaling rounding errors — Player area:": "重新调整舍入误差 - 玩家区域：",
    "The Horde Stirs": "部落觉醒",
    "Upkeep": "维护",
    "Troop Paths": "部队路径",
    "Total Hexes Captured": "总计占领六边形地块",
    "Total Captured Area": "总计占领区域",
    "Toggle route overlays.": "切换路线覆盖。",
    "Time Bank": "时间银行",
    "Threat": "威胁",
    "Thronefall": "王座陨落",
    "Trait": "特质",
    "Troops": "部队",
    "Troops Killed": "击杀部队",
    "Troops Lost": "损失部队",
    "Age": "时代",
    "Advance Age": "进步时代",
    "Advance to reshape the world": "继续努力，重塑世界",
    "Achv": "成就",
    "▶ Prologue Cinematic": "▶ 序章动画",
    "☠️ Kill Sovereign": "☠️ 击杀君主",
    "⚔️ Summon Horde": "⚔️ 召唤部落大军",
    "A ruler has fallen": "君主已陨落",
    "Active frontlines": "当前前线",
    "Banner of Claim": "占领旗帜",
    "Banner of Reckoning": "清算旗帜",
    "Base Hex Span": "基础地格范围",
    "Blood Price": "血之代价",
    "Bonus reward: +200 research points, +1% population growth": "额外奖励：+200 研究点数，+1% 人口增长",
    "Build Version": "构建版本",
    "Cache": "缓存",
    "Calculating": "计算中",
    "Complete Great Hearth Muster Beacons.": "点亮宏伟王城集结信标",
    "Complete Hearth Muster Beacons.": "点亮王城集结信标",
    "Complete Quest 8 to endure the horde taking your capital.": "完成任务8：抵御部落大军攻占都城",
    "Complete Quest 9 to destroy the horde.": "完成任务9：摧毁部落大军",
    "Complete Tutorial Quest 1 to kick off your dynasty.": "完成教程任务1：开启你的王朝",
    "Complete Tutorial Quest 2 to extend the legacy curve hard-cap.": "完成教程任务2：提升遗物曲线上限",
    "Complete Tutorial Quest 4 to steady your research cadence.": "完成教程任务4：稳定研究节奏",
    "Complete Tutorial Quest 5 to sharpen your frontline.": "完成教程任务5：巩固前线",
    "Complete your first research.": "完成首次研究",
    "Conquer your first tier 2 empire.": "征服首个二级帝国",
    "Distance Penalty": "距离衰减惩罚",
    "Distance to Capital": "与都城距离",
    "Distance-based falloff": "随距离衰减",
    "Dynastic Hearths": "王朝王城",
    "Dynastic Rite": "王朝仪式",
    "Dynastic Traits": "王朝特性",
    "Dynastic: Campfire Trails": "王朝：营火小径",
    "Dynastic: Eternal Rite": "王朝：永恒仪式",
    "Emberbound Vigor": "烬缚活力",
    "Empire Total Area": "帝国总面积",
    "Empires Conquered": "已征服帝国",
    "If copy fails on mobile, tap and hold the link field to copy it manually.": "若移动端复制失败，长按链接框手动复制",
    "Peak Population": "峰值人口",
    "Per-Tick Saves": "每刻自动保存",
    "Pop cap per hex:": "每地格人口上限：",
    "Population Cap": "人口上限",
    "Population Growth": "人口增长",
    "Population Overlay": "人口叠加显示",
    "Rescale Mastery": "重测精通等级",
    "Rescales": "重测参数",
    "Rescales:": "重测参数：",
    "Root Seed": "本源之种",
    "Routing": "路径规划",
    "Session Ticks": "会话计时",
    "Shield Wall": "盾墙",
    "Show red player troop path numbers": "显示红色玩家部队路径数值",
    "Sovereign bureaucratic efficiency has improved, and the realm has been rescaled. Administrative duties are now delegated more effectively.": "君主行政效率提升，疆域已重新规划。行政事务现已更高效地下放处理。",
    "Sovereign killed.": "君主已被击杀。",
    "Start Infinity Mode": "开始无尽模式",
    "Supply": "补给",
    "Tech": "科技",
    "The Border Musters": "边境集结",
    "The sovereign has passed.": "君主已逝世。",
    "Troop Split": "部队拆分",
    "Troop traverse:": "部队行进：",
    "Troops on Border": "边境驻军",
    "Veteran Muster": "老兵集结",
    "Visible Hexes": "可见地格",
    "Warrior Blood": "战士之血",
    "World Rescaled": "世界已重测",
    "Worldfire Muster": "战火集结",
    "Achievement Unlocked": "成就已解锁",
    "MAX": "最大",
    "Scouting": "侦察",
    "Enable population migration between your owned hexes.": "允许在您所拥有的方块之间进行人口迁移。",
    "◇ Ancient Wisdom": "◇ 远古智慧",
    "◇ Banner of Reckoning": "◇ 清算旗帜",
    "◇ Dynastic: Campfire Trails": "◇ 王朝：营火小径",
    "◇ Dynastic: Eternal Rite": "◇ 王朝：永恒仪式",
    "◇ Dynastic: Moon Rites": "◇ 王朝：月之祭典",
    "◇ Dynastic: Ring of Huts": "◇ 王朝：聚落环居",
    "◇ Dynastic: Scouting": "◇ 王朝：斥候侦查",
    "◇ Fertile Lands": "◇ 丰饶之地",
    "◇ Horde Tribute": "◇ 部落贡赋",
    "◇ Last Ember Omen": "◇ 余烬先兆",
    "◇ Warrior Blood": "◇ 战士之血",
    "A lingering ember ensures legacy never fully fades.": "一缕不灭余烬，确保遗物永不彻底熄灭。",
    "Ancient rites bless the soil of your domain.": "古老仪式为你的疆域土地赐福。",
    "Cost Sort ✓": "费用排序 ✓",
    "Crownbreaker I; Ashen Continuance Lv1": "破冠Ⅰ；灰烬永续 等级1",
    "Dynastic: Moon Rites": "王朝：月之祭典",
    "Dynastic: Ring of Huts": "王朝：聚落环居",
    "Dynastic: Scouting": "王朝：斥候侦查",
    "Dynastic: Staked Hide Shelters": "王朝：兽皮棚屋",
    "Each conquered empire fuels the dynasty with legacy.": "每征服一个帝国，都会为王朝补充遗物之力。",
    "Each generation inherits the martial prowess of ancestors.": "每一代人都继承先祖的武勇。",
    "Effect: +10 years to the legacy hard-cap per level": "效果：每级使遗物硬上限 +10 年",
    "Effect: +10 years to the legacy soft-cap per level": "效果：每级使遗物软上限 +10 年",
    "Effect: +15% population growth rate": "效果：人口增长率 +15%",
    "Effect: +20% player damage (matches Raiding Lessons)": "效果：玩家伤害 +20%（与掠夺心得效果一致）",
    "Effect: +25% research per tick": "效果：每刻研究点数 +25%",
    "Effect: After the hard cap, legacy gain continues at 1% of normal.": "效果：达到硬上限后，遗物获取以正常速率的1%继续生效",
    "Effect: Each level keeps 10.0k(m²) beyond the core 7 after rebirth.": "效果：每级可在转生后于核心7格外保留10.0k(㎡)疆域",
    "Effect: Effect: +100m leadership decay delay per level (combat leadership holds farther from the capital).": "效果：每级使统帅力衰减延迟 +100m（部队统帅力在远离都城时维持更久）",
    "Effect: Gain 50 legacy points per empire conquered (scaled by the legacy curve at conquest).": "效果：每征服一个帝国获得50点遗物点数（数值随征服时遗物曲线缩放）",
    "Effect: Gain 5000 legacy points each time the horde is defeated.": "效果：每击退一次部落大军获得5000点遗物点数",
    "Effect: Keeps Campfire Trails unlocked after rebirth.": "效果：转生后仍保留营火小径解锁状态",
    "Effect: Keeps Dynastic Rite unlocked after rebirth.": "效果：转生后仍保留王朝仪式解锁状态",
    "Effect: Keeps Moon Rites unlocked after rebirth.": "效果：转生后仍保留月之祭典解锁状态",
    "Effect: Keeps Ring of Huts unlocked after rebirth.": "效果：转生后仍保留聚落环居解锁状态",
    "Effect: Keeps Scouting unlocked after rebirth.": "效果：转生后仍保留斥候侦查解锁状态",
    "Effect: Keeps Staked Hide Shelters unlocked after rebirth.": "效果：转生后仍保留兽皮棚屋解锁状态",
    "Effect: Retain extra population after rebirth (scales by level).": "效果：转生后保留额外人口（随等级提升）",
    "Effect: Retain extra troops after rebirth (scales by level).": "效果：转生后保留额外部队（随等级提升）",
    "Fertile Lands Lv1; Banner of Claim Lv2": "丰饶之地 等级1；占领旗帜 等级2",
    "Full Cards ✓": "完整卡牌 ✓",
    "Hardened Trails": "坚实小径",
    "in the 🧪 Research tab to open the Legacy system.": "在🧪研究标签中打开遗物系统。",
    "Increase the population hard cap by 1 per 10.0k(m²) (taper region extends).": "每10.0k(㎡)疆域使人口硬上限+1（延伸衰减区域）。",
    "Makes Campfire Trails permanent across reigns.": "使营火小径在各代君主统治间永久保留。",
    "Makes Dynastic Rite permanent across reigns.": "使王朝仪式在各代君主统治间永久保留。",
    "Makes Moon Rites permanent across reigns.": "使月之祭典在各代君主统治间永久保留。",
    "Makes Ring of Huts permanent across reigns.": "使聚落环居在各代君主统治间永久保留。",
    "Makes Scouting permanent across reigns.": "使斥候侦查在各代君主统治间永久保留。",
    "Memories of past lives accelerate learning.": "往世记忆加速学识领悟。",
    "Moon Rites Lv1": "月之祭典 等级1",
    "Quest 1: Tutorial Quest 1": "任务1：教程任务1",
    "Research Campfire Trails 🧪. Open the 🧪 Research tab, earn points, and buy Campfire Trails.": "研究营火小径🧪。打开🧪研究标签，获取点数并购买营火小径。",
    "Ring of Huts Lv1": "聚落环居 等级1",
    "Scouting Lv1": "斥候侦查 等级1",
    "The fall of each horde swells your dynasty coffers.": "每击溃一支部落大军，王朝国库便愈加充盈。",
    "Unlocks the Legacy tab and enables dynastic trait purchases.": "解锁遗物标签并允许购买王朝特性。",
    "Warrior Blood Lv1; Crownbreaker Standards Lv1": "战士之血 等级1；破冠军旗 等级1",
    "Warrior Drums": "战士战鼓",
    "Boost research output by 50%.": "研究产出提升50%。",
    "Brushwood Barricades": "灌丛路障",
    "Fire-Keeper Lore": "守火者学识",
    "Hardened Trails": "坚实小径",
    "in the 🧪 Research tab to open the Legacy system.": "在🧪研究标签页中打开遗物系统。",
    "Increase base population growth per unit by 0.1 before distance decay.": "在距离衰减前，每单位基础人口增长+0.1。",
    "Increase the population soft cap by 1 per 10.0k(m²) (linear region extends).": "每10.0k(㎡)疆域使人口软上限+1（延伸线性区域）。",
    "Increase troop production in every hex by 25%.": "每个地格的部队产量提升25%。",
    "Knapped Spearpoints": "石制矛尖",
    "Layered Hide Armor": "多层兽皮甲",
    "Quest 1: Tutorial Quest 1": "任务1：教程任务1",
    "Raiding Lessons": "掠夺心得",
    "Research Campfire Trails 🧪. Open the 🧪 Research tab, earn points, and buy Campfire Trails.": "研究营火小径🧪。打开🧪研究标签页，获取点数并购买营火小径。",
    "Reveal the frontier around your conquered territory.": "揭开你征服领土周边的边境迷雾。",
    "Stacked hides and sinew add 0.1 hit points per level.": "堆叠的兽皮与筋腱，每级+0.1生命值。",
    "The Speakers of the Ember Fire": "烬火言者",
    "War Drum Muster": "战鼓集结",
    "Warrior Drums": "战士战鼓",
    "Woven Bark Shields": "编织树皮盾",
    "Dynastic: Brushwood Barricades": "王朝：灌丛路障",
    "Dynastic: Fire-Keeper Lore": "王朝：守火者学识",
    "Dynastic: Hardened Trails": "王朝：坚实小径",
    "Dynastic: Knapped Spearpoints": "王朝：石制矛尖",
    "Dynastic: Layered Hide Armor": "王朝：多层兽皮甲",
    "Dynastic: Raiding Lessons": "王朝：掠夺心得",
    "Dynastic: War Drum Muster": "王朝：战鼓集结",
    "Dynastic: Warrior Drums": "王朝：战士战鼓",
    "Dynastic: Woven Bark Shields": "王朝：编织树皮盾",
    "Quick Wit": "机敏才智",
    "The Antler-Painters": "绘角部落",
    "The Cave-Crown Band": "穴冠部族",
    "The Wolf Folk": "狼裔部族",
    "The Frost-Song Circle": "霜歌氏族",
    "The Mammoth-Crown People": "猛犸冠部族",
    "The River-Voice Tribe": "河语部落",
    "Locked": "未解锁",
    "Make player troops inflict 20% more casualties.": "使我方部队造成的伤亡提升20%",
    "Packed earth trails speed troop movement by 10 meters per tick.": "夯实土路可让部队每刻移动速度提升10米",
    "Stone-worked spearheads increase troop attack by 0.1 per level.": "石制矛头使部队攻击力每级提升0.1",
    "in the 👑 Legacy tab.": "在👑 遗物 标签页中",
    "Quest 2: Tutorial Quest 2": "任务2：教程任务2",
    "Research Dynastic Rite 👑. Open the 🧪 Research tab and unlock the rite to reveal legacy powers.": "研究王朝仪式👑。打开🧪研究标签并解锁该仪式，以显露遗物能力。",
    "Sovereign killed": "君主已阵亡",
    "Trigger your first succession by pressing": "按下以触发首次王位遗物",
    "Aran Siyajyss": "阿兰·西亚杰斯",
    "Legacy earned: 176 points (1 LP/year + 0.1 per 10.0k(m²) per year + 0.01 per population per year, scaled by the legacy curve). Legacy from conquered empires: 0.": "获得遗物：176 点数（每年 1 遗物点数 + 每 10.0k(㎡) 每年 0.1 + 每人口每年 0.01，受遗物曲线缩放）。来自征服帝国的遗物：0。",
    "Siyaj, the Fire-Bringer has passed.": "灭焰者 西亚杰斯 已逝世。",
    ", then spend legacy points in": "，然后花费遗物点数在",
    "Buy Dynastic: Campfire Trails. Make sure you have": "购买【王朝：营火小径】。确保你拥有",
    "Campfire Trails research": "营火小径 研究",
    "First Succession 👑. See your first ruler fall and an heir take the throne.": "首次遗物 👑。见证首位君主陨落，继承人登基。",
    "to make it permanent.": "使其效果永久生效。",
    "Need RP": "需要研究点",
    "✦ Fertile Lands": "✦ 肥沃土地",
    "✦ Last Ember Omen": "✦ 末烬预兆",
    "Dynastic Rite Lv1": "王朝仪式 1级",
    "◇ Dynastic: Brushwood Barricades": "◇ 王朝：灌木路障",
    "◇ Dynastic: Hardened Trails": "◇ 王朝：加固路径",
    "◇ Dynastic: Raiding Lessons": "◇ 王朝：掠夺研习",
    "◇ Dynastic: Woven Bark Shields": "◇ 王朝：编织树皮盾牌",
    "✦ Ancient Wisdom": "✦ 古老智慧",
    "✦ Dynastic: Campfire Trails": "✦ 王朝：篝火路径",
    "✦ Dynastic: Fire-Keeper Lore": "✦ 王朝：守火者学识",
    "✦ Dynastic: Ring of Huts": "✦ 王朝：茅屋环阵",
    "✦ Dynastic: Scouting": "✦ 王朝：侦察",
    "✦ Dynastic: War Drum Muster": "✦ 王朝：战鼓集结",
    "✦ Dynastic: Warrior Drums": "✦ 王朝：勇士战鼓",
    "✦ Quick Wit": "✦ 机智敏锐",
    "✦ Warrior Blood": "✦ 勇士血脉",
    "Brushwood Barricades Lv1": "灌木路障 1级",
    "Effect: +10% research per tick": "效果：每次刻度 +10% 研究进度",
    "Effect: Keeps Brushwood Barricades unlocked after rebirth.": "效果：重生后保持灌木路障解锁状态。",
    "Effect: Keeps Fire-Keeper Lore unlocked after rebirth.": "效果：重生后保持守火者学识解锁状态。",
    "Effect: Keeps Hardened Trails unlocked after rebirth.": "效果：重生后保持加固路径解锁状态。",
    "Effect: Keeps Knapped Spearpoints unlocked after rebirth.": "效果：重生后保持打制矛头解锁状态。",
    "Effect: Keeps Layered Hide Armor unlocked after rebirth.": "效果：重生后保持层叠兽皮护甲解锁状态。",
    "Effect: Keeps Raiding Lessons unlocked after rebirth.": "效果：重生后保持掠夺研习解锁状态。",
    "Effect: Keeps War Drum Muster unlocked after rebirth.": "效果：重生后保持战鼓集结解锁状态。",
    "Effect: Keeps Warrior Drums unlocked after rebirth.": "效果：重生后保持勇士战鼓解锁状态。",
    "Effect: Keeps Woven Bark Shields unlocked after rebirth.": "效果：重生后保持编织树皮盾牌解锁状态。",
    "Hardened Trails Lv1": "加固路径 1级",
    "Knapped Spearpoints Lv1": "打制矛头 1级",
    "Layered Hide Armor Lv1": "层叠兽皮护甲 1级",
    "Makes Brushwood Barricades permanent across reigns.": "使灌木路障在各代遗物中永久存在。",
    "Makes Fire-Keeper Lore permanent across reigns.": "使守火者学识在各代遗物中永久存在。",
    "Makes Hardened Trails permanent across reigns.": "使加固路径在各代遗物中永久存在。",
    "Makes Raiding Lessons permanent across reigns.": "使掠夺研习在各代遗物中永久存在。",
    "Makes War Drum Muster permanent across reigns.": "使战鼓集结在各代遗物中永久存在。",
    "Makes Warrior Drums permanent across reigns.": "使勇士战鼓在各代遗物中永久存在。",
    "Makes Woven Bark Shields permanent across reigns.": "使编织树皮盾牌在各代遗物中永久存在。",
    "Raiding Lessons Lv1": "掠夺研习 1级",
    "Reduce player casualties by 20% on defense.": "防守时玩家伤亡减少20%。",
    "Sharper minds remember more between reigns.": "更聪慧的头脑在各代遗物间能记住更多。",
    "Thick bark and wicker frames add +1 defense.": "厚实的树皮和柳条框架增加 +1 防御力。",
    "Woven Bark Shields Lv1": "编织树皮盾牌 1级",
    ", then": ", 然后",
    "✦ Dynastic: Brushwood Barricades": "✦ 王朝：灌木路障",
    "✦ Dynastic: Raiding Lessons": "✦ 王朝：掠夺研习",
    "Buy Dynastic: Campfire Trails 👑. First unlock Campfire Trails in 🧪 Research, then spend legacy points in the 👑 Legacy tab to make it permanent.": "购买“王朝：篝火路径” 👑。首先在 🧪“研究”中解锁“篝火路径”，然后在 👑“遗物”标签页中花费遗物点数使其永久生效。",
    "Capture an enemy hex 🌐. Select a frontier enemy hex, open its banner, and press Declare War to take territory.": "占领敌方六边形地块 🌐。选择一个边境敌方六边形地块，打开其旗帜，然后点击“宣战”以夺取领土。",
    "Capture an enemy hex 🌐. Select a frontier enemy hex, open its banner, and press Declare War.": "占领敌方六边形地块 🌐。选择一个边境敌方六边形地块，打开其旗帜，然后点击“宣战”。",
    "Crownbreaker II unlocked": "“破冠者II”已解锁",
    "DECLARE PEACE": "宣布和平",
    "Empire Conquered": "已征服帝国",
    "Enemy hexes captured": "已占领敌方六边形地块",
    "Extends troop production outward from the capital by 100 meters per level.": "每升一级，部队生产范围从首都向外扩展100米。",
    "New Age: Carved Stone": "新时代：雕刻石器时代",
    "Owned hexes": "已占领六边形地块",
    "Prepare the Age of Carved Stone by achieving Crownbreaker II 🏆, holding 100 owned hexes, and reaching 3,000 population with 3,000 troops.": "通过达成“破冠者II” 🏆、拥有100个已占领六边形地块、达到3000人口且拥有3000兵力，为“雕刻石器时代”做准备。",
    "Show enemy hex on map": "在地图上显示敌方六边形地块",
    "The Smoke Kin": "烟之氏族",
    "The Wolf-Drinkers": "饮狼血者氏族",
    "Total population": "总人口",
    "Total troops": "总兵力",
    "Unlock Warrior Drums 🧪. In 🧪 Research, take Staked Hide Shelters (level 1) → Scouting → Warrior Drums, saving points along the way.": "解锁“勇士战鼓” 🧪。在 🧪“研究”中，选择“鞣制兽皮庇护所（1级）”→“侦察”→“勇士战鼓”，沿途节省点数。",
    "Unlock Warrior Drums. In 🧪 Research, buy": "解锁“勇士战鼓”。在 🧪“研究”中，购买",
    "CONQUERED": "已征服",
    "Effect: Keeps Hearth Muster Beacons unlocked after rebirth.": "效果：重生后保持炉灶集结信标解锁状态。",
    "Extends troop production outward from the capital by 150 meters per level after the Stone Age rescale.": "在石器时代调整规模后，每升一级，部队生产范围从首都向外扩展150米。",
    "Show Population Numbers": "显示人口数字",
    "Effect: Each level keeps 1.00e+4m² beyond the core 7 after rebirth.": "效果：每次重生后，每个等级都会在核心区域之外额外保留 1.00e+4 平方米的空间。",
    "Unlock Level": "解锁等级",
    "The Blood-Song People": "血歌族",
    "The Mammoth Circle": "猛犸象圆圈",
    "The Smoke People": "烟雾族",
    "The Antler Lineage": "鹿角氏族",
    "The Blood-Watchers": "血卫氏族",
    "The Frost-Crown Lineage": "霜冠氏族",
    "The River Band": "河畔帮",
    "The River-Painters": "河畔画师氏族",
    "The Smoke-Eaters": "吞烟者氏族",
    "The Speakers of the Flint Sky": "燧石天空的言说者氏族",
    "The Ash-Drinkers": "饮灰者",
    "The Cave-Drinkers": "饮洞者",
    "The People of the Wolf Cave": "狼穴之民",
    "The Stone-Chasers": "追石族",
    "The Ash-Song People": "灰歌族",
    "The Antler-Hide Lineage": "鹿角兽皮族",
    "The Children of the Ash Deep": "灰渊之子",
    "The Children of the Bone Cave": "骨洞之子",
    "The Speakers of the Antler Deep": "鹿角渊的言说者",
    "Aran Siyajyss, the River-Watcher has passed.": "阿兰·西雅吉思，那位河畔守望者已逝。",
    "Dynastic: Great Hearth Muster Beacons": "王朝：大型炉灶集结信标",
    "Effect: Keeps Great Hearth Muster Beacons unlocked after rebirth.": "效果：重生后保持大型炉灶集结信标处于解锁状态。",
    "Legacy earned: 300 points (1 LP/year + 0.1 per 1.00e+4m² per year + 0.01 per population per year, scaled by the legacy curve). Legacy from conquered empires: 0.": "获得遗物点数：300点（每年1点遗物点数 + 每1.00×10⁴平方米每年0.1点 + 每人每年0.01点，依遗物曲线缩放）。来自被征服帝国的遗物点数：0。",
    "Tav Siyajyss": "塔夫·西雅吉思",
    "The Frost-Crown Circle": "霜冠之环",
    "The Frost-Gift Tribe": "霜赐部落",
    "The Horde-Chasers": "逐部落者",
    "The Horde-Hunters": "猎部落者",
    "The People of the Wolf Meadow": "狼之草地的居民",
    "The River-Chasers": "逐河者",
    "The Smoke-Hide Family": "烟皮家族",
    "The Smoke-Shadow Family": "烟影家族",
    "The Wolf Family": "狼族",
    "\"the Fire-Bringer\"": "“火种携带者”",
    "\"the River-Watcher\"": "“河畔守望者”",
    "The Blood Circle": "血之环",
    "The People of the Frost Valley": "霜谷之民",
    "The Speakers of the Cave Deep": "洞穴深渊的言说者",
    "Roric Siyajyss": "罗里克·西亚吉斯",
    "Tav Siyajyss, the Earth-Keeper has passed.": "塔夫·西亚杰斯，地球守护者已经离世了。",
    "Roric Siyajyss, the Earth-Keeper has passed.": "罗里克·西雅吉思，那位大地守护者已逝。",
    "The Bone-Gift Circle": "骨赐之环",
    "The Horde-Scar Tribe": "部落伤疤部落",
    "The Speakers of the Horde Hunt": "部落狩猎的言说者",
    "The Thunder-Painters": "雷之画师",
    "The Blood-Hunters": "血猎者",
    "The Cave-Song Folk": "洞穴歌者",
    "The Frost-Walkers": "霜行者",
    "The Smoke-Painters": "烟之画师",
    "The Mammoth People": "猛犸族",
    "The Thunder-Crown Family": "雷冠家族",
    "Magan Siyajyss": "马甘·西雅吉思",
    "": "",
    "Aran Siyajyss, the Spirit-Guide has passed.": "阿兰·西雅吉思，那位灵魂向导已逝。",
    "Magan Siyajyss": "马甘·西亚杰斯",
    "The Children of the Ember Fire": "烬火之子",
    "The Ember Circle": "烬环部族",
    "The Ember-Watchers": "烬火守望者",
    "The Frost Tribe": "霜寒部族",
    "The Guardians of the Blood Cave": "血穴守护者",
    "The Guardians of the Cave Fire": "穴火守护者",
    "The Horde-Followers": "部落追随者",
    "The Keepers of the Stone Cave": "石穴守御者",
    "The Stone Family": "石氏部族",
    "The Wardens of the Mammoth Deep": "深丘猛犸守境者",
    "Acquire Dynastic: Defend, research Border Drills, then destroy the horde.": "获得【王朝：固守】，研究边境操练，随后摧毁部落大军。",
    "Crownbreaker Standards Lv1": "破冠军旗 等级1",
    "Defend": "固守",
    "Defend against the Horde": "抵御部落大军",
    "Dynastic: Defend acquired": "已获得【王朝：固守】",
    "Fertile Lands Lv1": "丰饶之地 等级1",
    "Grom Siyajyss": "格罗姆·西亚杰斯",
    "Horde destroyed": "部落大军已覆灭",
    "No bonus available.": "无额外奖励可领取",
    "No further ages": "无后续时代",
    "No further ages.": "无后续时代",
    "Quest 7: New Age: Carved Stone": "任务7：新纪元：刻石时代",
    "Quest 8: the Horde": "任务8：抵御部落大军",
    "quest goals are not known yet": "任务目标暂未解锁",
    "Redistributes up to 30% (+10% per level) per tick, scaled by troop speed / hex span, between contiguous border edges fighting the same empire.": "每刻可将最多30%兵力（每级额外+10%），根据部队速度/地格范围折算，重新调配至与同一帝国交战的相邻边境战线。",
    "Settlements rise in enduring stone, and the world stretches wider.": "聚落以坚石永存，世界疆域愈发辽阔。",
    "Unlock defense stance controls against contested empires.": "解锁针对敌对帝国的防御姿态操控权限。",
    "War Drum Muster Lv1": "战鼓集结 等级1",
    "You have reached the final known age.": "你已抵达当前已知的最终时代。",
    "The Flint-Shadow Band": "燧石暗影乐队",
    "The Barley Field-Keepers": "麦田守族",
    "The Seed Kin": "禾种亲族",
    "The Barley Clan": "大麦部族",
    "The Clan of the Serpent Sunstone Granary": "蛇阳石谷仓氏族",
    "The Seed Barley Hearths": "禾种大麦聚落",
    "The Stonefield Seed Hold": "石田种仓守族",
    "The Timber Hearth Harvesters": "木居采穗部族",
    "The Timber Hearth Lineage": "木居血脉部族",
    "The Tribe of the Oakhaven Timber Grove": "橡林木禾部族",
    "A mysterious enemy has appeared and is destroying empires, burning the land in its wake.": "一个神秘的敌人出现了，正在摧毁各个帝国，沿途烧毁着大地。",
    "The map whispers of a roaming horde. Its march is relentless.": "地图上透露出一股游荡大军的气息。它的行进毫无停歇。",
    "◇ Dynastic: Defend": "◇ 王朝：固守",
    "✦ Dynastic: Hardened Trails": "✦ 王朝：坚实小径",
    "Defend Lv1": "固守 等级1",
    "Dynastic: Border Drills": "王朝：边境操练",
    "Dynastic: Defend": "王朝：固守",
    "Dynastic: Shieldwall Drills": "王朝：盾墙操练",
    "Effect: Keeps Border Drills unlocked after rebirth.": "效果：转生后仍保留边境操练解锁状态",
    "Effect: Keeps Defend unlocked after rebirth.": "效果：转生后仍保留固守解锁状态",
    "Effect: Keeps Shieldwall Drills unlocked after rebirth.": "效果：转生后仍保留盾墙操练解锁状态",
    "Gain +1% defense per level while in defense mode.": "防御形态下，每级防御力 +1%",
    "Gain +2% troop attack vs the horde.": "对部落大军作战时，部队攻击力 +2%",
    "Horde Omens": "部落凶兆",
    "Makes Defend permanent across reigns.": "使固守在历代传承间永久保留。",
    "Mara Siyajyssen": "玛拉·西亚杰森",
    "Reveal the time until the next horde and boost troop production by 10% per level while at war with the horde.": "可显示距离下一次部落来袭的剩余时间；与部落大军交战期间，每级部队产量 +10%。",
    "Siege Rituals": "围城仪式",
    "The Stonefield Seed Hearths": "石田种仓部族",
    "The Barley Stonefield Hold": "大麦石田守族",
    "The Clay-Pot Granary Potters": "陶瓮谷仓陶工部族",
    "The Clay-Pot Villagers": "陶瓮村落部族",
    "The Oakhaven Tillers": "橡林耕者部族",
    "The Sunstone Seed Lineage": "阳石禾种血脉",
    "The Tribe of the Barley Stonefield Hollow": "大麦石田幽谷部族",
    "The Bone People": "骨族",
    "The Clan of the Serpent Field": "蛇野氏族",
    "The Folk of the Seed Granary": "谷仓禾民",
    "The Hold of the Hearth Hill": "丘炉守族",
    "The Serpent Sunstone Clan": "蛇阳石氏族",
    "The Serpent Sunstone Masons": "蛇阳石石匠部族",
    "The Serpent Sunstone Potters": "蛇阳石陶工部族",
    "The Stone-Song Kin": "石歌亲族",
    "The Stonefield Masons": "石田石匠部族",
    "The Timber Hearth Weavers": "木居织者部族",
    "The Tribe of the Stonefield Rise": "石田高丘部族",
    "Defend against the Horde; Horde Omens": "抵御部落大军；部落凶兆",
    "Frontier Omens": "边境凶兆",
    "Reveal the threat level of each rival empire along the frontier.": "显示边境周边所有敌对帝国的威胁等级。",
    "A huge horde with 100k troops has arrived at your border.": "十万大军的庞大部落已抵达边境。",
    "A vicious horde overran the capital, killed the ruler in a bloody massacre, then swept onward to ravage other lands before vanishing.": "凶残的部落攻陷都城，君王惨遭屠戮，随后大军肆虐四方，之后便销声匿迹。",
    "Peace was declared with all other empires at war. All border troops have been called to battle this formidable enemy.": "与所有交战帝国缔结和平条约，所有边境军队尽数调遣，迎战此强敌。",
    "Resume": "继续",
    "Infinity Conquest": "无限征服",
    "Unlock the Infinity tab and allow a one-way shift into Infinite Conquest until rebirth.": "解锁“无限”选项卡，并允许进行一次单向的“无限征服”转变，直至重生。",
    "Mountain Province": "山区行省",
    "The Clay-Pot Folk": "陶瓮部族",
    "The Clay-Pot Hearth Kin": "陶炉亲族",
    "The Hearth Folk": "炉居部族",
    "The Hearth Granary Builders": "谷仓营建部族",
    "The Kin of the Clay-Pot Hearth Furrow": "陶炉田垄亲族",
    "The Kin of the Granary Barley Granary": "大麦仓亲族",
    "The Serpent Kin": "蛇族",
    "The Sunstone Stonefield Masons": "阳石石匠部族",
    "The Timber Hearth Builders": "木居营建部族",
    "\"the Ancestor-Speaker\"": "先祖诵者",
    "\"the Earth-Keeper\"": "大地守御者",
    "\"the Hearth-Keeper\"": "炉灶守护者",
    "\"the Hunt-Master\"": "狩猎大师",
    "\"the Sky-Watcher\"": "天穹守望者",
    "\"the Spirit-Guide\"": "灵韵引路人",
    "Asha Siyajyssen": "阿莎·西亚杰森",
    "Fen Siyajyss": "芬·西亚杰斯",
    "Hrak Siyajyss": "赫拉克·西亚杰斯",
    "Kor Siyajyss": "科尔·西亚杰斯",
    "Rhea Siyajyssen": "蕾娅·西亚杰森",
    "The Hearths of the Barley Stonefield Hollow": "大麦石田幽谷炉居部族",
    "The Timber Hearth Masons": "木居石匠部族",
    "HORDE ARRIVED": "",
    "HORDE ARRIVED": "部落来袭",
    "Horde is active": "部落军队出动",
    "The Bone Host": "骨之大军",
    "The Hold of the Clay-Pot Hearth Hollow": "陶炉幽谷守族",
    "The Hold of the Timber Hearth Granary": "木居谷仓守族",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Desert Province": "沙漠",
    "Forest Province": "森林",
    "Grass Province": "草原",
    "Capital Province": "首都",
    "--s": "--秒",
    "Ad +30m": "Ad +30m",
    "Mem": "Mem",
    "Obj": "目标",
    "Tick Interval": "Tick 间隔",
    "Ticks": "Tick",
    "Tick": "Tick",
    "Siyaj": "Siyaj",
    "Join Discord": "加入 Discord",
    "FPS": "FPS",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "✅": "✅",
    "⚙": "⚙",
    "◀": "◀",
    "♾️": "♾️",
    "❌": "❌",
    "🌐": "🌐",
    "🧪": "🧪",
    "🧭": "🧭",
    "🪨": "🪨",
    "🛠": "🛠",
    "🏆": "🏆",
    "👑": "👑",
    "📊": "📊",
    "📜": "📜",
    "⚔️": "⚔️",
    "⋯": "⋯",
    "⏳": "⏳",
    "▶": "▶",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Event year: ": "事件年份: ",
    "Reign #": "统治 #",
    "Hard: ": "硬: ",
    "Soft: ": "软: ",
    "Rescale Map": "调整地图",
    "Autosave in ": "自动保存于 ",
    "Compact ": "紧凑 ",
    "\"the Sky-Watcher\" — Age ": "“天穹守望者” - 年 ",
    "\"the Hearth-Keeper\" — Age ": "“守炉人” - 年 ",
    "\"the Spirit-Guide\" — Age ": "\“灵魂向导\” - 年 ",
    "\"the River-Watcher\" — Age ": "“河流观察者” - 年 ",
    "\"the Hunt-Master\" — Age ": "“狩猎大师” - 年 ",
    "\"the Fire-Bringer\" — Age ": "“引火使者” - 年 ",
    "\"the Earth-Keeper\" — Age ": "“地球守护者” - 年 ",
    "\"the Clan-Chieftain\" — Age ": "“部族首领” - 年 ",
    "Requires: Achievement ": "要求: 成就 ",
    "Requires: ": "要求: ",
    "The dynasty burns bright longer before the legacy curve softens. (": "王朝遗物曲线软化前，将延续更久。(",
    "Your line endures longer before the legacy curve hardens. (": "你的血脉在遗物曲线硬化前，将存续更久。(",
    "Your standard marks lands that remain yours between reigns. (": "你的旗帜标记着历代君主统御的疆土。(",
    "Embers of past reigns rekindle life in the core at rebirth. Keeps 12 population on rebirth. (": "往昔王朝的余烬在转生时重燃核心生机，转生时保留12人口。(",
    "Old warbands answer the call of each new sovereign. Keeps 40 troops on rebirth. (": "古老战团响应每位新君的召唤，转生时保留40部队。(",
    "◇ Ashen Continuance (Level ": "◇ 灰烬永续（等级 ",
    "◇ Banner of Claim (Level ": "◇ 占领旗帜（等级 ",
    "◇ Crownbreaker Standards (Level ": "◇ 破冠军旗（等级 ",
    "◇ Dynastic Hearths (Level ": "◇ 王朝王城（等级 ",
    "◇ Emberbound Vigor (Level ": "◇ 烬缚活力（等级 ",
    "◇ Veteran Muster (Level ": "◇ 老兵集结（等级 ",
    "◇ Dynastic: Staked Hide Shelters (Level ": "◇ 王朝：兽皮棚屋（等级",
    "Battle standards carry the sovereign's command further from the capital. (": "战旗能将君主的号令传至更远的都城之外。（",
    "Crownbreaker Standards (Level ": "破冠军旗（等级",
    "Dynastic Hearths (Level ": "王朝王城（等级",
    "Ashen Continuance (Level ": "灰烬永续（等级 ",
    "Banner of Claim (Level ": "占领旗帜（等级 ",
    "◇ Dynastic: Staked Hide Shelters (Level ": "◇ 王朝：兽皮棚屋（等级",
    "Emberbound Vigor (Level ": "烬缚活力（等级",
    "Staked Hide Shelters": "兽皮棚屋",
    "Makes Staked Hide Shelters permanent across reigns. (": "使兽皮棚屋在各代君主统治间永久保留。（",
    "Veteran Muster (Level ": "老兵集结（等级",
    "Knapped Spearpoints (Level ": "分层兽皮护甲（等级 ",
    "Layered Hide Armor (Level ": "石制矛尖（等级 ",
    "✦ Ashen Continuance (Level ": "✦ 灰烬永续 (等级 ",
    "✦ Dynastic: Staked Hide Shelters (Level ": "✦ 王朝：鞣制兽皮庇护所（等级",
    "◇ Dynastic: Knapped Spearpoints (Level ": "◇ 王朝：打制矛头（等级",
    "✦ Emberbound Vigor (Level ": "✦ 烬缚活力（等级",
    "◇ Dynastic: Layered Hide Armor (Level ": "◇ 王朝：层叠兽皮护甲（等级",
    "Makes Knapped Spearpoints permanent across reigns. (": "使打制矛头在各代遗物中永久存在。（",
    "Makes Layered Hide Armor permanent across reigns. (": "使层叠兽皮护甲在各代遗物中永久存在。（",
    "Hearth Muster Beacons": "炉灶集结信号灯",
    "The Horde-Drinkers": "部落酒鬼",
    "The Cave-Shadow Folk": "洞穴阴影族",
    "The Keepers of the Frost Sky": "冰天之守卫者",
    "The Bone-Chasers": "逐骨者",
    "The Smoke-Followers": "逐烟者",
    "The Thunder-Followers": "逐雷者",
    "Dynastic: Hearth Muster Beacons": "王朝时代：炉火集结信号灯",
    "Great Hearth Muster Beacons": "伟大的壁炉集合信标",
    "The Blood-Shadow People": "血影族",
    "The Wolf-Scar People": "狼痕族",
    "Water Province": "水乡",
    "The Thunder-Shadow Folk": "雷影族",
    "◇ Dynastic: Fire-Keeper Lore": "◇ 王朝：守火者学识",
    "◇ Dynastic: Hearth Muster Beacons": "◇ 王朝：炉灶集结信标",
    "◇ Dynastic: War Drum Muster": "◇ 王朝：战鼓集结",
    "◇ Dynastic: Warrior Drums": "◇ 王朝：勇士战鼓",
    "Makes Hearth Muster Beacons permanent across reigns. (": "使炉灶集结信标在各代遗物中永久存在。（",
    "Age of Carved Stone; Hearth Muster Beacons level ": "雕刻石器时代；炉灶集结信标等级 ",
    "◇ Dynastic: Great Hearth Muster Beacons": "◇王朝：大壁炉集合信标",
    "Makes Great Hearth Muster Beacons permanent across reigns. (": "使伟大的壁炉集合的信标在统治中永久存在。(",
    "Border Drills": "边境演习",
    "✦ Banner of Claim": "✦ 申明旗帜",
    "✦ Crownbreaker Standards": "✦ 冠军突破标准",
    "◇ Dynastic: Shieldwall Drills": "◇ 王朝：盾墙操练",
    "✦ Dynastic Hearths": "✦ 王朝王城",
    "✦ Veteran Muster": "✦ 老兵集结",
    "◇ Dynastic: Border Drills": "◇ 王朝：边境操练",
    "Embers of past reigns rekindle life in the core at rebirth. Adds +25 kept population on rebirth. (": "历代君主的余烬在转生时重燃核心生机，**转生额外保留25人口**。（",
    "Old warbands answer the call of each new sovereign. Adds +60 kept troops on rebirth. (": "古老战团响应每位新君的召唤，**转生额外保留60部队**。（",
    "Horde Omens": "部落凶兆",
    "Makes Border Drills permanent across reigns. (": "使边境操练在历代传承间永久保留。（",
    "Makes Shieldwall Drills permanent across reigns. (": "使盾墙操练在历代传承间永久保留。（",
    "Shieldwall Drills": "盾墙操练",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    ' IX': ' IX',
    " (m)": " (m)",
    " researched": " 已研究",
    " (Hard Cap)": " (硬上限)",
    " (hexes)": " (地块)",
    " (default)": " (默认)",
    " (Capital)": " (首都)",
    " (HTML)": " (HTML)",
    " owned)": " 已拥有)",
    " (next level)": " (下一级)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+)k\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^([\d\.]+)\/([\d\.]+)\)$/,
    /^达到(.+)$/,
    /^教程任务(.+)$/,
    /^失去(.+)$/,
    /^遥远(.+)$/,
    /^总计(.+)$/,
    /^征服(.+)$/,
    /^在单次(.+)$/,
    /^占领(.+)$/,
    /^生成(.+)$/,
    /^奖励(.+)$/,
    /^击杀(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^ \(([\d\.]+)\:([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)\% \(([\d\.]+)\/([\d\.]+)\)$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)× \– ([\d\.]+)×$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)k\(m²\)$/,
    /^([\d\.]+) m²$/,
    /^([\d\.]+) km²$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)m² → ([\d\.,]+)m²$/,
    /^([\d\.,]+) m² → ([\d\.,]+) m²$/,
    /^([\d\.,]+) → ([\d\.,]+)$/,
    /^([\d\.,]+)m → ([\d\.,]+)m$/,
    /^([\d\.,]+) m → ([\d\.,]+) m$/,
    /^([\d\.,]+)m$/,
    /^([\d\.,]+)m²$/,
    /^([\d\.,]+)MB$/,
    /^([\d\.,]+)ms$/,
    /^([\d\.,]+) m$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\#([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)×$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\-([\d\.,]+)\%$/,
    /^([\d\.]+)e\-([\d\.,]+)×$/,
    /^([\d\.]+)e\-([\d\.,]+)× \- ([\d\.]+)×$/,
    /^([\d\.]+)e\-([\d\.,]+)× \- ([\d\.]+)e\-([\d\.,]+)×$/,
    /^([\d\.]+)e\+([\d\.,]+)m²$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^Capture (.+) of enemy land.$/, '占领 $1 敌人的土地。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Legacy earned: (.+) points \((.+) LP\/year \+ (.+) per (.+) per year \+ (.+) per population per year, scaled by the legacy curve\). Legacy from conquered empires: (.+).$/, '遗产收益：$1 点（每年 $2 遗物点 + $3 每 $4 每年 +  $5 每人口每年，根据遗产曲线进行调整）。征服帝国获得的遗产：$6。'],
    [/^Bonus reward: (.+) LP, (.+) research points$/, '加成奖励: $1 遗物点数, $2 研究点数'],
    [/^Soft cap (.+)y · Hard cap (.+)y · Gain (.+) LP\/yr$/, '软上限 $1 年 · 硬上限 $2 年 · 每年获得 $3 遗物点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^\+([\d\.]+)\/s$/, '+$1\/秒'],
    [/^\+([\d\.]+)\/sec$/, '+$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^\+([\d\.]+)e\-([\d\.,]+)\/s$/, '+$1e-$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) RP$/, '$1 研究点'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^Reward: (.+) kept area after rebirth$/, '奖励: +$1% 重生后的保留区域'],
    [/^Reward: \+([\d\.]+)\% defensive efficiency$/, '奖励: +$1% 防守效率'],
    [/^Reward: \+([\d\.]+)\% troop attack$/, '奖励: +$1% 部队攻击'],
    [/^Reward: \+([\d\.]+)\% troop production$/, '奖励: +$1% 部队生产'],
    [/^Reward: \+([\d\.]+)\% troops per tick production$/, '奖励: +$1% 部队每Tick生产'],
    [/^Reward: \+([\d\.]+) frontline troops instantly$/, '奖励: +$1 前线部队立即'],
    [/^Reward: \+([\d\.]+) year to legacy hard-cap$/, '奖励: +$1 年到遗物硬上限'],
    [/^Reward: \+([\d\.]+) research point per second$/, '奖励: +$1 研究点数每秒'],
    [/^Reward: \+([\d\.]+) troops per tick production$/, '奖励: +$1 部队每Tick生产'],
    [/^Reward: \+([\d\.]+)\% troop defense$/, '奖励: +$1% 部队防御'],
    [/^Reward: \+([\d\.]+)\% research speed$/, '奖励: +$1% 研究速度'],
    [/^Reward: \+([\d\.]+)\% max population hard cap$/, '奖励: +$1% 最大人口硬上限'],
    [/^Reward: \+([\d\.]+)\% defense vs horde$/, '奖励: +$1% 防守对于部落'],
    [/^Reward: \+([\d\.]+)\% offense vs horde$/, '奖励: +$1% 进攻对于部落'],
    [/^Reward: \+([\d\.]+)\% population growth$/, '奖励: +$1% 人口增长'],
    [/^OFF ([\d\.]+)\%$/, '关闭 $1%'],
    [/^DEF ([\d\.]+)\%$/, '防御 $1%'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^✦ ([\d\.,]+) Legacy Points$/, '✦ $1 遗物点数'],
    [/^✦ ([\d\.,]+)(.+) Legacy Points$/, '✦ $1$2 遗物点数'],
    [/^✦ ([\d\.,]+) Legacy Points \(\+([\d\.,]+) pending\)$/, '✦ $1 遗物点数 (+$2 待定)'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.,]+) Troops$/, '+$1 部队'],
    [/^\+([\d\.,]+) LP$/, '+$1 遗物点数'],
    [/^\+([\d\.,]+) Research$/, '+$1 研究'],
    [/^\+([\d\.,]+)s delta$/, '+$1s 三角洲'],
    [/^([\d\.,]+) hex$/, '$1 六边形地块'],
    [/^([\d\.,]+) hexes • ([\d\.,]+) troops$/, '$1 六边形地块 • $2 部队'],
    [/^([\d\.,]+) hexes • ([\d\.,]+)(.+) troops$/, '$1 六边形地块 • $2$3 部队'],
    [/^([\d\.,]+)🔓$/, '$1🔓'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)y$/, '$1 年'],
    [/^Reigned for ([\d\.,]+) years.$/, '在位 $1 年。'],
    [/^Autosave in ([\d\.,]+)s$/, '自动保存于 $1秒后'],
    [/^Farflung Throne ([\d\.,]+)$/, '遥远的王座 $1'],
    [/^Hold territory at least ([\d\.,]+) m from the capital.$/, '占领距离首都至少 $1 米 的领土。'],
    [/^Conquer ([\d\.,]+) empires.$/, '征服 $1 敌人。'],
    [/^Conquer ([\d\.,]+) empires that declared war on you first.$/, '征服 $1 先向你宣战的帝国。'],
    [/^Conquer ([\d\.,]+) tier ([\d\.,]+) empires.$/, '征服 $1 层级 $2 敌人。'],
    [/^Lose ([\d\.,]+) troops.$/, '失去 $1 部队。'],
    [/^Produce ([\d\.,]+) total troops.$/, '总计生产 $1 部队。'],
    [/^Reach ([\d\.,]+) peak population.$/, '达到 $1 人口峰值。'],
    [/^Reach ([\d\.,]+) rescales in a single run.$/, '在单次运行中达到 $1 重新缩放。'],
    [/^Kill ([\d\.,]+) horde troops.$/, '击杀 $1 部落部队。'],
    [/^Kill ([\d\.,]+) enemy troops.$/, '击杀 $1 敌军部队。'],
    [/^Generate ([\d\.,]+) total population.$/, '生成 $1 总人口。'],
    [/^Tutorial Quest ([\d\.,]+)$/, '教程任务 $1'],
    [/^Tutorial Quest ([\d\.,]+)$/, '教程任务 $1'],
    [/^Quest ([\d\.,]+): Tutorial Quest ([\d\.,]+)$/, '任务 $1: 教程任务 $2'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Campfire Trails Lv([\d\.,]+)$/, '营火小径 等级 $1'],
    [/^▶ UNLOCK \(([\d\.,]+) LP\)$/, '▶ 解锁 ($1 遗物点数)'],
    [/^▶ UNLOCK LEVEL ([\d\.,]+) \(([\d\.,]+) LP\)$/, '▶ 解锁等级 $1 ($2 遗物点数)'],
    [/^ \(Level ([\d\.,]+)\/([\d\.,]+)\)$/, ' (等级 $1/$2)'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^ level([\d\.,]+)$/, ' 等级 $1'],
    [/^ level ([\d\.,]+)$/, ' 等级 $1'],
    [/^ Lv([\d\.,]+)$/, ' 等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Died Age ([\d\.,]+)\nReigned ([\d\.,]+)y\n✦ ([\d\.,]+) LP$/, '死亡时代 $1\n统治 $2 年\n✦ $3 遗物点数'],
    [/^Died Age ([\d\.,]+)\nReigned ([\d\.,]+)y\n✦ ([\d\.,]+)(.+) LP$/, '死亡时代 $1\n统治 $2 年\n✦ $3$4 遗物点数'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^([\d\.,]+) seconds → ([\d\.,]+) seconds$/, '$1 秒 → $2 秒'],
    [/^([\d\.,]+)\/([\d\.,]+) completed$/, '$1\/$2 已完成'],
    [/^([\d\.,]+)\/([\d\.,]+) unlocked$/, '$1\/$2 已解锁'],
    [/^([\d\.,]+) \/ ([\d\.,]+) completed$/, '$1 \/ $2 已完成'],
    [/^([\d\.,]+) \/ ([\d\.,]+) unlocked$/, '$1 \/ $2 已解锁'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) RP$/, '$1 研究点'],
    [/^✦ (.+) Legacy Points \(\+(.+) pending\)$/, '✦ $1 遗物点数 (+$2 待定)'],
    [/^🔒 (.+) Legacy Points$/, '🔒 $1 遗物点数'],
    [/^🔒 LEVEL (.+) LP$/, '🔒 等级 $1 遗物点数'],
    [/^Legacy earned: (.+) points.$/, '遗物收益：$1 点数。'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);